filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
        - 'spec/*'
        - 'stub/*'
        - 'coverage/*'
        - 'vendor/*'
checks:
  php: true
tools:
  external_code_coverage:
    timeout: 1200
    runs: 4
  php_code_coverage: false
